### ISSUE TITLE
游戏登录器在哪？

### ISSUE THREAD

**Issue by mykright** [1995chen/dnf#1]
遇到的几个问题
1，如果宿主机已经安装了mysql，或者3306端口被占用，初始化会失败

2，游戏登录器没找到在哪

**Comment by onlyGuo** [comment]
进入docker容器看了下，里面有用的统一登陆器的网关文件, 可以用统一登陆器试试，我的登录是自己写的，你可以参考一下：
https://github.com/onlyGuo/dnf-client-public.git
重点是服务端生成token，需要配置公私钥，公钥放到容器内的game文件夹，私钥用来生成token，以java算法为例：
````java
        // 得到待加密的用户标识, 假设我要登录的用户的UID是1(用户UID是查询的`d_taiwan`.`accounts`表)
        int uid = 1;
        String data = String.format("%08x0101010101010101010101010101010101010101010101010101010101010101559145100" +
                "10403030101", uid);
        data = String2Hex.convertHexToString(data);
        // 加密计算出用户授权Key
        String privateKey = new String(MinFieldUtil.readResource("private.key")).replace("\r", "")
                .replace("\n", "");
        byte[] resultByte = RSATool.encryptByPrivateKey(data.getBytes(), privateKey);
        return Base64.getEncoder().encodeToString(resultByte);

````
客户端拿到token后调用外部命令:
````
string token = "xxxxxxxxxxxxxxxxxxx";
Window.Shell.exec("DNF.exe " + token);
````

**Comment by onlyGuo** [comment]
一些工具类是我自己封装的，整体的登录算法如下：
1. `预加密串` = `用户ID` + `08x010101010101010101010101010101010101010101010101010101010101010155914510010403030101`;
2. `加密串` = RSA加密(`预加密串`, `私钥`);
3. `TOKEN` = 转BASE_64(`加密串`);
4. 客户端执行`DNF.exe ` + `TOKEN`;
日过自己单机玩的话，可以获取到token了以后直接在客户端建立一个bat文件，内容就写（吧xxxx换成你计算好的token）：
`DNF.exe xxxxxx`

**Comment by 1995chen** [comment]
fixed in centos6_85

**Comment by 1995chen** [comment]
兄弟，欢迎提Pr

**Comment by NeroBlackstone** [comment]
> 大概率不是，token错误会在选择频道时弹出错误，提前闪退可能是某些兼容问题，linux的话可以先切到vm环境试试。
> 
> 
> 
> ---原始邮件---
> 发件人: "Nero ***@***.***&gt;
> 发送时间: 2025年9月20日(周六) 中午12:57
> 收件人: ***@***.***&gt;;
> 抄送: ***@***.******@***.***&gt;;
> 主题: Re: [1995chen/dnf] 游戏登录器在哪？ (#1)
> 
> 
> NeroBlackstone left a comment (1995chen/dnf#1)
>   
> 一些工具类是我自己封装的，整体的登录算法如下：
>   
> 预加密串 = 用户ID + 08x010101010101010101010101010101010101010101010101010101010101010155914510010403030101;
>  
> 加密串 = RSA加密(预加密串, 私钥);
>  
> TOKEN = 转BASE_64(加密串);
>  
> 客户端执行DNF.exe  + TOKEN;
>  日过自己单机玩的话，可以获取到token了以后直接在客户端建立一个bat文件，内容就写（吧xxxx换成你计算好的token）：
>  DNF.exe xxxxxx
>    
> 打扰，我在linux下wine运行客户端，我计算出token以后，启动客户端，在选频道前会闪退，这是token没算对的原因吗？
>  
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID: ***@***.***&gt;

非常感谢您的解答♥️♥️♥️
