### ISSUE TITLE
添加ARM64服务器docker镜像支持

### ISSUE THREAD

**Issue by IceDerce** [1995chen/dnf#12]
请构建的时候添加支持，please

**Comment by XanderYe** [comment]
没有dnf源码，只有x86的二进制文件，所以没法支持arm服务器

**Comment by IceDerce** [comment]
> 没有dnf源码，只有x86的二进制文件，所以没法支持arm服务器

好吧，我忘记了，源码是x86架构的

**Comment by momomobinx** [comment]
可以尝试配置docker 多架构支持

**Comment by TheKingV5** [comment]
> 可以尝试配置docker 多架构支持

能行吗？ARM64
