### ISSUE TITLE
没有固定IP怎么办，有DDNS

### ISSUE THREAD

**Issue by VergilGao** [1995chen/dnf#13]
难道每次IP变动的时候都要修改登录器吗？

**Comment by XanderYe** [comment]
环境变量AUTO_PUBLIC_IP 可以启动容器时自己获取公网ip，自动重启的话需要自己写脚本去检测并重启容器

**Comment by XanderYe** [comment]
另外客户端使用统一网关登录器+DOF7补丁，支持域名配置；统一补丁貌似不能用域名。

**Comment by VergilGao** [comment]
感谢！
