### ISSUE TITLE
连接频道信息失败

### ISSUE THREAD

**Issue by 371942171** [1995chen/dnf#17]
hosts设置了start.dnf.tw，还是失败
![image](https://user-images.githubusercontent.com/54466733/177030649-1041d8b1-141e-4f59-8537-ff3df8631717.png)

**Comment by 371942171** [comment]
解决了，得修改配置文件

**Comment by sroads** [comment]
怎么修改呀老哥

**Comment by 371942171** [comment]
> 怎么修改呀老哥

我记得，就是你下载那个dof7补丁后，里面会有个config文件，里面有地址改成服务器地址试试，忘了
