### ISSUE TITLE
进入公益服后没有频道

### ISSUE THREAD

**Issue by MVsualStdio** [1995chen/dnf#21]
docker配置成功服务器启东，客户端进入公益服后没有频道

**Comment by MVsualStdio** [comment]
host也改了

**Comment by 1995chen** [comment]
* A: 检查Linux服务端防火墙是否关闭
* A: 检查云服务器厂商相关端口是否放开
* A: 五国未成功跑出
2.服务端不出五国
* A: 机器内存不够，swap未配置或配置后未生效，通过free -m查看swap占用内存
* A: 服务器磁盘空间是否足够
* A: 如果更换过PVF,请确保PVF是未加密的，而且需要同步更换对应的等级补丁
* A: 机器内存低于2G可以尝试修改--shm-size=2g或1g
