### ISSUE TITLE
登录器连不上网关，怎么处理？

### ISSUE THREAD

**Issue by zhaoeryu** [1995chen/dnf#22]
<img width="1066" alt="image" src="https://user-images.githubusercontent.com/49333146/202097503-d381dff6-48c6-4270-b7db-ec19ca19ebd9.png">

**Comment by dongziyudongziyu** [comment]
同问

**Comment by dongziyudongziyu** [comment]
我换了1995chen/dnf:stable 这个版本的镜像

**Comment by 1995chen** [comment]
建议更换最新的镜像。
连接不上网关一般是五国没跑出来，或者Linux服务器防火墙未关闭或云服务器厂商端口未放开
