### ISSUE TITLE
我按照步骤安装 报错了,我重试了两次

### ISSUE THREAD

**Issue by menggangaaa** [1995chen/dnf#23]
我按照步骤安装 报错了,我重试了两次,每次都是先全部删除镜像和/data下所有内容,然后先执行数据库,再执行服务端
因为本机的7000 和 7001端口已使用 我在docke往外端口时用了17000和17001 我的理解应该不会有问题才对,而且日志中的错误没找到原因,我还修改了gm密码和外网ip,但我觉得不应该受到这个影响才对
系统CentOS 7.9.2009 x86_64(Py3.7.9)
执行服务端命令如下,数据库命令直接仓库中复制的
`docker run -d -e PUBLIC_IP=X.X.X.X -e DNF_DB_ROOT_PASSWORD=88888888 -e GM_ACCOUNT=gm_user -e GM_PASSWORD=6xxxxxxx6a -v /data/log:/home/neople/game/log -v /data/mysql:/var/lib/mysql -v /data/data:/data -p 3000:3306/tcp -p 7600:7600/tcp -p 881:881/tcp -p 20303:20303/tcp -p 20303:20303/udp -p 20403:20403/tcp -p 20403:20403/udp -p 40403:40403/tcp -p 40403:40403/udp -p 17000:7000/tcp -p 17000:7000/udp -p 17001:7001/tcp -p 17001:7001/udp -p 7200:7200/tcp -p 7200:7200/udp -p 10011:10011/tcp -p 31100:31100/tcp -p 30303:30303/tcp -p 30303:30303/udp -p 30403:30403/tcp -p 30403:30403/udp -p 10052:10052/tcp -p 20011:20011/tcp -p 20203:20203/tcp -p 20203:20203/udp -p 30703:30703/udp -p 11011:11011/udp -p 2311-2313:2311-2313/udp -p 30503:30503/udp -p 11052:11052/udp --cpus=1 --memory=1g --memory-swap=-1 --shm-size=8g --name=dnf 1995chen/dnf:centos6-2.0.2`
日志文件如下:
[Log20221124.log](https://github.com/1995chen/dnf/files/10082157/Log20221124.log)
[Log20221124.init.log](https://github.com/1995chen/dnf/files/10082158/Log20221124.init.log)
[Log20221124.cri.log](https://github.com/1995chen/dnf/files/10082159/Log20221124.cri.log)

**Comment by Esimorp** [comment]
same

**Comment by 1995chen** [comment]
应该不要紧，继续等待加载地图。这个过程会比较长。
7000端口和7001端口不能够随意替换。
