### ISSUE TITLE
可否将启动服务的命令从systemctl更换为service？

### ISSUE THREAD

**Issue by 735589187** [1995chen/dnf#26]
用docker pull下来后如果是用systemctl start mysqld总会出现Failed to get D-Bus connection: Operation not permitted的问题，这好像是因为docker的权限问题导致,可否更改为用service命令启动？如果你觉得麻烦，可以说下如何让用户自己修改吗？

**Comment by Kiteflyingee** [comment]
请问解决了吗？

**Comment by 735589187** [comment]
> 请问解决了吗？

还没，作者不处理我也没招，虽然可以perviledge进去，但运行仍然会出现D-BUS错误

**Comment by 1995chen** [comment]
这个问题可以不处理，不影响正常使用
