### ISSUE TITLE
一直频道信息接收失败是什么原因

### ISSUE THREAD

**Issue by tuqiasa** [1995chen/dnf#29]

**Comment by tuqiasa** [comment]
![image](https://github.com/1995chen/dnf/assets/27683601/2cf1ae9b-bf40-4cfa-b6a6-237293a13285)

**Comment by tuqiasa** [comment]
前面都是正常的 就是频道加载不出来

**Comment by AemonCao** [comment]
同样的问题，有解决方法了嘛？

**Comment by AnmLobby** [comment]
一样，没办法用

**Comment by 1995chen** [comment]
* A: 检查服务端防火墙是否关闭
* A: 检查云服务器厂商相关端口是否放开
* A: 客户端windows是否配置hosts
