### ISSUE TITLE
docker没有报错日志，siroco52中init日志一直卡在Init DataManager ...

### ISSUE THREAD

**Issue by lrs-960** [1995chen/dnf#30]
<img width="1152" alt="无标题" src="https://github.com/1995chen/dnf/assets/65840470/b7874eb3-ec8f-4c58-8a42-b2e0cd278a7f">
<img width="1152" alt="2" src="https://github.com/1995chen/dnf/assets/65840470/f023a40b-25f5-4ac1-8683-e02798ff76a7">

**Comment by cander0815** [comment]
我也是，请问最后要怎么解决？
docker 的版本 Version:           24.0.7，
系统版本： CentOS Linux release 7.9.2009 (Core)

**Comment by AlexJinx** [comment]
兄弟，怎么解决的？
