### ISSUE TITLE
问，进不去频道，就是主频道还是灰的。

### ISSUE THREAD

**Issue by xuehrs** [1995chen/dnf#36]
还有3306可以不用改为3000吗？

测试过7001端口，发现没开和这文件df_game_r有关吗？
和这文件权限有关吗？

**Comment by 1995chen** [comment]
可以不用改3000，3000端口主要是用于网关连接用的，可以随意更改，没有限制。
df_game_r需要具有可执行权限，如果df_game_r执行失败，就会有问题。

**Comment by xuehrs** [comment]
谢谢你的回答，我已经改为kvm emu来使用，目前测试良好centos6 docker目前不能安装了centos7 docker安装centos6运行dnfOK！改了几个地方，等有空帮你修正下信息。2024年4月24日 下午3:27，"Tony.Chen" ***@***.***>写道：
可以不用改3000，3000端口主要是用于网关连接用的，可以随意更改，没有限制。
df_game_r需要具有可执行权限，如果df_game_r执行失败，就会有问题。
