### ISSUE TITLE
登录器登录时报错

### ISSUE THREAD

**Issue by nygula** [1995chen/dnf#4]
使用2018年2月份的客户端登录时.总是报错数组下标索引出错

**Comment by 1995chen** [comment]
能贴上具体的配置以及报错信息吗

**Comment by 1995chen** [comment]
加QQ群一起交流：852685848

**Comment by nygula** [comment]
![](https://i.loli.net/2021/11/29/i9YKUOse4GqFvun.png)
QQ群好像没法搜索到.

**Comment by 1995chen** [comment]
我上午设置的不可被搜索我没看见，现在可以搜索了

**Comment by 1995chen** [comment]
PVF 加密问题，重新加密一下pvf，记得连接网关后，点击获取密钥，然后点击加密，（不要点击生成密钥！！！这是问题原因）

**Comment by 1995chen** [comment]
![image](https://user-images.githubusercontent.com/19407551/144434313-a0717950-1eb3-4d65-929e-dad90df88275.png)
