### ISSUE TITLE
请把登录器放置于游戏跟根目录下什么意思？

### ISSUE THREAD

**Issue by Zaku0222** [1995chen/dnf#42]
统一网管在线工具可以连接服务器网关，密码也生成了，也同样生成了登录器。但是在登录时提示“请把登录器放置于游戏根目录下”。根目录不是位于服务器 /root下吗，那里已经有一个Config.ini了，登录器放置于根目录下是指把.exe放在/root下吗？还是生成登录器时同步生成的Config.ini放在/root下？那样不会覆盖吗？

**Comment by 1995chen** [comment]
登陆器要放到windows DNF客户端目录下 和DNF.exe在一个目录
