### ISSUE TITLE
关于使用1995chen/dnf:centos5-2.1.4.fix1镜像，dnf-console启动报错

### ISSUE THREAD

**Issue by musha233** [1995chen/dnf#44]
报错日志如下：
`./main: /lib64/libc.so.6: version 'GLIBC_2.14' not found (required by ./main)`

大佬麻烦帮忙看下，是否是哪边配置有问题

**Comment by 1995chen** [comment]
这个插件缺少依赖，回头我看下

**Comment by 1995chen** [comment]
插件已经更新，下载最新版本的插件替换
