### ISSUE TITLE
Docker 在国内访问日益困难，有考虑其他部署方式嘛

### ISSUE THREAD

**Issue by Cat7373** [1995chen/dnf#45]
比如通过 Github Action 的 cron 任务，每日推送到 ttl.sh 一份，有效期 1 天，这样能多个下载途径（大部分国内机器 ttl.sh 还是好用的，不过也碰到过无法连接的）

**Comment by Cat7373** [comment]
[临时解决方案一（虽然仍然很慢很难用失败率很高但起码能用）：](https://gist.github.com/y0ngb1n/7e8f16af3242c7815e7ca2f0833d3ea6)

1. 写到 /etc/docker/daemon.json 文件里：
  ```json
  {
      "registry-mirrors": [
          "https://docker.m.daocloud.io",
          "https://mirror.iscas.ac.cn"
      ]
  }
  ```
2. 执行 systemctl daemon-reload
3. 执行 systemctl restart docker

**Comment by Cat7373** [comment]
[自建 Docker 代理方案（亲测国内阿里云杭州机器可用，需要自己有域名，不需要备案）](https://github.com/ImSingee/hammal)

**Comment by 1995chen** [comment]
registry.cn-hangzhou.aliyuncs.com/1995chen/dnf:centos7-2.1.4.fix1
先用这个

**Comment by Cat7373** [comment]
这个好，虽然免费版有并发限制，但考虑到体量，也是够用的

**Comment by Cat7373** [comment]
这个好，虽然免费版有并发限制，但考虑到体量，也是够用的
