### ISSUE TITLE
建立数据库初始化的时候报错，没反应，不会出日志

### ISSUE THREAD

**Issue by skyshenma** [1995chen/dnf#6]
建立数据库初始化的时候报错，没反应，不会出日志。
使用命令如下：
`docker run --rm -v /opt/dnf/log:/home/neople/game/log -v /opt/dnf/mysql:/var/lib/mysql -v /opt/dnf/data:/data 1995chen/dnf:stable /bin/bash /home/template/init/init.sh
`
输入完命令之后，不出日志，直接跳过，如图：
![image](https://user-images.githubusercontent.com/67644756/145950697-06f282a9-409e-4d0c-b814-b185e7d27be8.png)

**Comment by 1995chen** [comment]
使用1995chen/dnf:centos7-latest这个镜像
